name: Desplegar a GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ajusta a tu versión de Node.js

      - name: Install dependencies
        run: npm install # O yarn install

      - name: Build
        run: npm run build # O yarn build

      - name: Deploy to GitHub Pages
        run: |
          echo "Directorio de trabajo actual: $(pwd)"
          ls -al ./dist
          git checkout --orphan gh-pages
          git reset --hard
          rm -rf *
          cp -r ./dist/. .
          git add .
          git commit -m "Desplegar sitio a gh-pages (intento de copia explícito)"
          git push origin gh-pages --force