ame: Desplegar a GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para obtener el historial completo

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ajusta a tu versión de Node.js

      - name: Install dependencies
        run: npm install # O yarn install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          # Copia todo el contenido del repositorio ANTES de limpiar
          cp -r * .
          git reset --hard
          rm -rf *
          cp -r dist/. .
          git add .
          git commit -m "Desplegar sitio a gh-pages (copia antes de limpiar)"
          git push origin gh-pages --force