name: Desplegar a GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ajusta a tu versión de Node.js

      - name: Install dependencies
        run: npm install # O yarn install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          rm -rf *
          find dist -type f -print0 | xargs -0 -I {} cp "{}" .
          find dist -type d -print0 | xargs -0 -I {} mkdir -p "{}"
          find dist -type f -print0 | xargs -0 -I {} cp "{}" .
          git add .
          git commit -m "Desplegar sitio a gh-pages (copia explícita de archivos y carpetas)"
          git push origin gh-pages --force